
# Jekyll config
auto: true
exclude:
  - CNAME
  - Makefile
  - README.md
lsi: false
pygments: true
safe: true
server: true

# Site details
lang: en-GB
host: pigeon.rowanmanning.com
tld: rowanmanning.com

# Repo details
repo:
  url: https://github.com/rowanmanning/pigeon
  raw: https://raw.github.com/rowanmanning/pigeon
  branch: develop

# Author details
author:
  name: Rowan Manning
  url: http://rowanmanning.com/

# Tracking info
ga: UA-32567673-1
